<a href="https://colab.research.google.com/github/gdkim0522/assign3_slime_AI/blob/main/Assignment3_Slime.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [315]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn.linear_model
from mpl_toolkits.mplot3d import Axes3D

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

#from IPython.display import display, Markdown, Latex
from IPython.display import Markdown as md

X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

<span style='color:Black;font-size: 250%'># Part 1. Loading the dataset</span>

In [316]:
#Load dataset remotely
df = pd.read_csv("https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv")

#Display first 15 rows
result = df.head(15)
print(result)

#Display summary of table information
df.info()

    Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature °C  1000 non-null   int64  
 1   Mols KCL        1000 non-null   int64  
 2   Size nm^3       1000 n

<span style='color:Black;font-size: 250%'># Part 2. Splitting the dataset</span>

In [317]:
# Take the pandas dataset and split it into our features (X) and label (y)
features = df.iloc[:,0:2]
label = df.iloc[:,2:3]

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
train_data, test_data = train_test_split(df, test_size=0.1, random_state = 25)

# Take the pandas dataset and split it into our features (X) and label (y)
X_train_data = train_data.iloc[:,0:2]
Y_train_data = train_data.iloc[:,2:3]

X_test_data = test_data.iloc[:,0:2]
Y_test_data = test_data.iloc[:,2:3]


<span style='color:Black;font-size: 250%'># Part 3. Perform Linear Regression</span>

In [318]:
# Create linear regression object
regr = linear_model.LinearRegression()

regr.fit(X_train_data, Y_train_data)

# Make predictions using the testing set
Y_test_pred = regr.predict(X_test_data)
regr.predict([[300, 400]])

array([[258404.33014083]])

This value of the size in nm seems reasonable given the original dataset.

In [319]:
# The coefficients
print("Coefficients: \n", regr.coef_)
# The intercept
print("Intercept: \n", regr.intercept_)
# The score
print("Score: \n", regr.score(X_test_data, Y_test_data))

"""
# The coefficients
print("Coefficients 1: \n", regr.coef_.index(0))
# The coefficients
print("Coefficients 1: \n", regr.coef_.index(1))
"""

a=2
print(a)

Coefficients: 
 [[ 878.74381809 1044.28874415]]
Intercept: 
 [-422934.31294534]
Score: 
 0.8490438915970394
2


md(f"data {a}")
The score value is $\sqrt{{a}}$ is pretty much consistent in terms of being reliable since it close to the value of 1.

The score value is {{regr.score(X_test_data, Y_test_data)}} is pretty much consistent in terms of being reliable since it close to the value of 1.
Euler $$ e^{i \pi} + 1 = 0 regr.coef_ $$ 
Coeff $$ e^{i \pi} + 1 = 0 regr.score(X_test_data, Y_test_data) $$ 
$h(x) = {{regr.coef_}}$

display(Markdown(f'The value of a is {a}'))

<span style='color:Black;font-size: 250%'># Part 4. Use Cross Validation</span>

In [320]:
kf5 = KFold(n_splits=5, shuffle=False)
kf3 = KFold(n_splits=5, shuffle=False)

#cross_val_score(regr, X_test_data, Y_test_data, cv=5)

#One thousand
cross_val_score(regr, features, label, cv=5)

array([0.83918826, 0.87051239, 0.85871066, 0.87202623, 0.84364641])

Using the cross validation feature, the score values ranges from 0.84 to 0.87.
This is pretty much consistent in terms of being reliable in predicitng any data point.

<span style='color:Black;font-size: 250%'># Part 5. Perform Polynomial Regression</span>

In [321]:
from sklearn.preprocessing import PolynomialFeatures

#Using PolynomialFeatures and perform regression on augmented datast of degree 2
poly = PolynomialFeatures(degree=2)
poly_train = poly.fit_transform(X_train_data)
poly_test = poly.fit_transform(X_test_data)

regr = linear_model.LinearRegression()
regr.fit(poly_train, Y_train_data)


# Report metrics and output resultant equation.
print("Coefficients: \n", regr.coef_[0][5])
# The intercept
print("Intercept: \n", regr.intercept_)
# The score
print("Score: \n", regr.score(poly_test, Y_test_data))

Coefficients: 
 0.02857142871413702
Intercept: 
 [2.06597033e-05]
Score: 
 1.0


The score value is $regr.score(poly_test, Y_test_data)$ is 1, and it shows that polynomial regression of degree 2 is better than linear regression in terms of estimating values of data points.
Euler $$ e^{i \pi} + 1 = 0$$