<a href="https://colab.research.google.com/github/gdkim0522/assign3_slime_AI/blob/main/Assignment3_Slime.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


In [293]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn.linear_model
from mpl_toolkits.mplot3d import Axes3D

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

#from IPython.display import display, Markdown, Latex
from IPython.display import Markdown as md




X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

<span style='color:Black;font-size: 250%'># Part 1. Loading the dataset</span>

In [294]:
#Load dataset remotely
#df = pd.read_csv("data/science_data_large.csv")
df = pd.read_csv("https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv")
#https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv

#Display first 15 rows
result = df.head(15)
print(result)

#Display summary of table information
df.info()

    Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature °C  1000 non-null   int64  
 1   Mols KCL        1000 non-null   int64  
 2   Size nm^3       1000 n

<span style='color:Black;font-size: 250%'># Part 2. Splitting the dataset</span>

In [295]:
# Take the pandas dataset and split it into our features (X) and label (y)
features = df.iloc[:,0:2]
label = df.iloc[:,2:3]

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
train_data, test_data = train_test_split(df, test_size=0.1, random_state = 25)

# Take the pandas dataset and split it into our features (X) and label (y)
X_train_data = train_data.iloc[:,0:2]
Y_train_data = train_data.iloc[:,2:3]

X_test_data = test_data.iloc[:,0:2]
Y_test_data = test_data.iloc[:,2:3]


<span style='color:Black;font-size: 250%'># Part 3. Perform Linear Regression</span>

In [296]:
# Create linear regression object
regr = linear_model.LinearRegression()

#regr.fit(temp_C_train, size_nm3_train)
regr.fit(X_train_data, Y_train_data)

# Make predictions using the testing set
#size_nm3_pred = regr.predict(temp_C_test)
Y_test_pred = regr.predict(X_test_data)
regr.predict([[300, 400]])

array([[258404.33014083]])

In [297]:
# The coefficients
print("Coefficients: \n", regr.coef_)
# The intercept
print("Intercept: \n", regr.intercept_)
# The score
print("Score: \n", regr.score(X_test_data, Y_test_data))

"""
# The coefficients
print("Coefficients 1: \n", regr.coef_.index(0))
# The coefficients
print("Coefficients 1: \n", regr.coef_.index(1))
"""

a=2
print(a)

Coefficients: 
 [[ 878.74381809 1044.28874415]]
Intercept: 
 [-422934.31294534]
Score: 
 0.8490438915970394
2


md(f"data {a}")
The score value is $\sqrt{{a}}$ is pretty much consistent in terms of being reliable since it close to the value of 1.

The score value is {{regr.score(X_test_data, Y_test_data)}} is pretty much consistent in terms of being reliable since it close to the value of 1.
Euler $$ e^{i \pi} + 1 = 0 regr.coef_ $$ 
Coeff $$ e^{i \pi} + 1 = 0 regr.score(X_test_data, Y_test_data) $$ 
$h(x) = {{regr.coef_}}$

display(Markdown(f'The value of a is {a}'))

<span style='color:Black;font-size: 250%'># Part 4. Use Cross Validation</span>

In [298]:
kf5 = KFold(n_splits=5, shuffle=False)
kf3 = KFold(n_splits=5, shuffle=False)

#cross_val_score(regr, X_test_data, Y_test_data, cv=5)

#One thousand
cross_val_score(regr, features, label, cv=5)

array([0.83918826, 0.87051239, 0.85871066, 0.87202623, 0.84364641])

Using the cross validation feature, the score values ranges from 0.84 to 0.87.
This is pretty much consistent in terms of being reliable in predicitng any data point.

<span style='color:Black;font-size: 250%'># Part 5. Perform Polynomial Regression</span>

In [299]:
from sklearn.preprocessing import PolynomialFeatures

#Using PolynomialFeatures and perform regression on augmented datast of degree 2
poly = PolynomialFeatures(degree=2)
poly_train = poly.fit_transform(X_train_data)
poly_test = poly.fit_transform(X_test_data)

regr = linear_model.LinearRegression()
regr.fit(poly_train, Y_train_data)


# Report metrics and output resultant equation.
print("Coefficients: \n", regr.coef_[0][5])
# The intercept
print("Intercept: \n", regr.intercept_)
# The score
print("Score: \n", regr.score(poly_test, Y_test_data))

Coefficients: 
 0.02857142871413702
Intercept: 
 [2.06597033e-05]
Score: 
 1.0


The score value is $regr.score(poly_test, Y_test_data)$ is 1, and it shows that polynomial regression of degree 2 is better than linear regression in terms of estimating values of data points.
Euler $$ e^{i \pi} + 1 = 0$$

In [300]:
"""
print(train_data)
print('=============  Middle =============')

print(test_data)
"""



# Make predictions using the testing set
#size_nm3_pred = regr.predict(temp_C_test)
"""
Y_test_pred = regr.predict(poly_test)
regr.predict([[300, 400]])
"""
print(poly_train)
print(len(poly_train))
print(len(poly_train[0]))


"""
# The coefficients
print("Coefficients: \n", regr.coef_)
# The intercept
print("Intercept: \n", regr.intercept_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(X_test_data, Y_test_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(X_test_data, Y_test_pred))
"""

"""
# Plot outputs
plt.scatter(temp_C_test, size_nm3_test, color="black")
plt.plot(temp_C_test, size_nm3_pred, color="blue", linewidth=3)
"""

"""
# Plot outputs
fig = plt.figure(figsize=(12, 12))

ax = fig.add_subplot(projection='3d')
ax.scatter(X_test_data.iloc[:,0:1], X_test_data.iloc[:,1:2], Y_test_data, color="black")
ax.set_xlabel("Temp")`
ax.set_ylabel("KCL")
ax.set_zlabel("Size")
#ax.plot(X_test_data.iloc[:,0:1], X_test_data.iloc[:,1:2], Y_test_pred, color="blue", linewidth=3)
#ax.plot_surface(X_test_data.iloc[:,0:1], X_test_data.iloc[:,1:2], Y_test_pred, color="blue", alpha=0.5)


ax.xticks(())
ax.yticks(())


plt.show()
"""








"""
# The coefficients
print("Coefficients: \n", poly.coef_)
# The intercept
print("Intercept: \n", poly.intercept_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(X_test_data, Y_test_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score([[300, 400]], Y_test_pred))


print(X_train_data)
print(Y_train_data)

print(X_test_data)
print(Y_test_data)
"""



"""
X = df.iloc[:,0:2]
#print(X)

Y = df.iloc[:,2:3]
#print(Y)
print(X_train_data)
print(Y_train_data)

print(X_test_data)
print(Y_test_data)

temp_C_train = train_data.iloc[:,0]
KCL_mols_train = train_data.iloc[:,1]
size_nm3_train = train_data.iloc[:,2]

print(temp_C_train)
print(size_nm3_train)


temp_C_test = test_data.iloc[:,0]
KCL_mols_test = test_data.iloc[:,1]
size_nm3_test = test_data.iloc[:,2]
"""

#


"""

[1, a, b, a^2, ab, b^2]
# The coefficients
print("Coefficients: \n", poly.coef_)
# The intercept
print("Intercept: \n", poly.intercept_)
# The score
print("Score: \n", poly.score(X_test_data, Y_test_data))

# Poly train
print("Poly train: \n", poly_train)

# Poly test
print("Poly test: \n", poly_test)
"""


[[1.00000e+00 2.20000e+02 6.80000e+01 4.84000e+04 1.49600e+04 4.62400e+03]
 [1.00000e+00 4.24000e+02 3.80000e+02 1.79776e+05 1.61120e+05 1.44400e+05]
 [1.00000e+00 3.06000e+02 1.69000e+02 9.36360e+04 5.17140e+04 2.85610e+04]
 ...
 [1.00000e+00 3.52000e+02 9.50000e+02 1.23904e+05 3.34400e+05 9.02500e+05]
 [1.00000e+00 6.84000e+02 5.00000e+00 4.67856e+05 3.42000e+03 2.50000e+01]
 [1.00000e+00 6.91000e+02 7.92000e+02 4.77481e+05 5.47272e+05 6.27264e+05]]
900
6


'\n\n[1, a, b, a^2, ab, b^2]\n# The coefficients\nprint("Coefficients: \n", poly.coef_)\n# The intercept\nprint("Intercept: \n", poly.intercept_)\n# The score\nprint("Score: \n", poly.score(X_test_data, Y_test_data))\n\n# Poly train\nprint("Poly train: \n", poly_train)\n\n# Poly test\nprint("Poly test: \n", poly_test)\n'

In [301]:
# Load the diabetes dataset
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

# Use only one feature
diabetes_X = diabetes_X[:, np.newaxis, 2]

print(diabetes_X)

print('=============  Middle =============')

print(diabetes_y)


# Split the data into training/testing sets
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:] 


# Split the targets into training/testing sets
diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(temp_C_train, diabetes_y_train)

# Make predictions using the testing set
diabetes_y_pred = regr.predict(diabetes_X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(diabetes_y_test, diabetes_y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(diabetes_y_test, diabetes_y_pred))

# Plot outputs
plt.scatter(diabetes_X_test, diabetes_y_test, color="black")
plt.plot(diabetes_X_test, diabetes_y_pred, color="blue", linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()




[[ 0.06169621]
 [-0.05147406]
 [ 0.04445121]
 [-0.01159501]
 [-0.03638469]
 [-0.04069594]
 [-0.04716281]
 [-0.00189471]
 [ 0.06169621]
 [ 0.03906215]
 [-0.08380842]
 [ 0.01750591]
 [-0.02884001]
 [-0.00189471]
 [-0.02560657]
 [-0.01806189]
 [ 0.04229559]
 [ 0.01211685]
 [-0.0105172 ]
 [-0.01806189]
 [-0.05686312]
 [-0.02237314]
 [-0.00405033]
 [ 0.06061839]
 [ 0.03582872]
 [-0.01267283]
 [-0.07734155]
 [ 0.05954058]
 [-0.02129532]
 [-0.00620595]
 [ 0.04445121]
 [-0.06548562]
 [ 0.12528712]
 [-0.05039625]
 [-0.06332999]
 [-0.03099563]
 [ 0.02289497]
 [ 0.01103904]
 [ 0.07139652]
 [ 0.01427248]
 [-0.00836158]
 [-0.06764124]
 [-0.0105172 ]
 [-0.02345095]
 [ 0.06816308]
 [-0.03530688]
 [-0.01159501]
 [-0.0730303 ]
 [-0.04177375]
 [ 0.01427248]
 [-0.00728377]
 [ 0.0164281 ]
 [-0.00943939]
 [-0.01590626]
 [ 0.0250506 ]
 [-0.04931844]
 [ 0.04121778]
 [-0.06332999]
 [-0.06440781]
 [-0.02560657]
 [-0.00405033]
 [ 0.00457217]
 [-0.00728377]
 [-0.0374625 ]
 [-0.02560657]
 [-0.02452876]
 [-0.01806

NameError: name 'temp_C_train' is not defined

In [ ]:
 X_train, X_test, y_train, y_test = titanic(
...     'Temperature °C', 'Mols KCL', test_size=0.33, C)

In [ ]:
"""
# Train the model using the training sets
temp_C_train = temp_C_train.values.reshape(-1, 1)
size_nm3_train = size_nm3_train.values.reshape(-1, 1)
temp_C_test = temp_C_test.values.reshape(-1, 1)


print(X_train_data)
print(Y_train_data)

print(X_test_data)
print(Y_test_data)
print(X_test_data.iloc[:,0:1])
print(X_test_data.iloc[:,1:2])

"""

"""

"""



"""
#temp_C = df.iloc[:,0]
#KCL_mols = df.iloc[:,1]
#size_nm3 = df.iloc[:,2]

#print(temp_C)
#print(size_nm3)


# Create linear regression object
regr = linear_model.LinearRegression()


# Train the model using the training sets
regr.fit(temp_C_train, size_nm3_train)

# Make predictions using the testing set
size_nm3_pred = regr.predict(temp_C_test)



# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(size_nm3_test, size_nm3_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(size_nm3_test, size_nm3_pred))

# Plot outputs
plt.scatter(temp_C_test, size_nm3_test, color="black")
plt.plot(temp_C_test, size_nm3_pred, color="blue", linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()
"""

"""
print(X_test_data)
print(Y_test_data)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(X_test_data, Y_test_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score([[300, 400]], Y_test_pred))
"""