In [309]:
<a href="https://colab.research.google.com/github/gdkim0522/assign3_slime_AI/blob/main/Assignment3_Slime.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

SyntaxError: invalid syntax (<ipython-input-309-7fb8c97d7866>, line 1)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn.linear_model
from mpl_toolkits.mplot3d import Axes3D

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

#from IPython.display import display, Markdown, Latex
from IPython.display import Markdown as md

X, y = np.arange(10).reshape((5, 2)), range(5)
X

<span style='color:Black;font-size: 250%'># Part 1. Loading the dataset</span>

In [ ]:
#Load dataset remotely
df = pd.read_csv("https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv")

#Display first 15 rows
result = df.head(15)
print(result)

#Display summary of table information
df.info()

<span style='color:Black;font-size: 250%'># Part 2. Splitting the dataset</span>

In [310]:
# Take the pandas dataset and split it into our features (X) and label (y)
features = df.iloc[:,0:2]
label = df.iloc[:,2:3]

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
train_data, test_data = train_test_split(df, test_size=0.1, random_state = 25)

# Take the pandas dataset and split it into our features (X) and label (y)
X_train_data = train_data.iloc[:,0:2]
Y_train_data = train_data.iloc[:,2:3]

X_test_data = test_data.iloc[:,0:2]
Y_test_data = test_data.iloc[:,2:3]


<span style='color:Black;font-size: 250%'># Part 3. Perform Linear Regression</span>

In [311]:
# Create linear regression object
regr = linear_model.LinearRegression()

regr.fit(X_train_data, Y_train_data)

# Make predictions using the testing set
Y_test_pred = regr.predict(X_test_data)
regr.predict([[300, 400]])

array([[258404.33014083]])

This value of the size in nm seems reasonable given the original dataset.

In [312]:
# The coefficients
print("Coefficients: \n", regr.coef_)
# The intercept
print("Intercept: \n", regr.intercept_)
# The score
print("Score: \n", regr.score(X_test_data, Y_test_data))

"""
# The coefficients
print("Coefficients 1: \n", regr.coef_.index(0))
# The coefficients
print("Coefficients 1: \n", regr.coef_.index(1))
"""

a=2
print(a)

Coefficients: 
 [[ 878.74381809 1044.28874415]]
Intercept: 
 [-422934.31294534]
Score: 
 0.8490438915970394
2


md(f"data {a}")
The score value is $\sqrt{{a}}$ is pretty much consistent in terms of being reliable since it close to the value of 1.

The score value is {{regr.score(X_test_data, Y_test_data)}} is pretty much consistent in terms of being reliable since it close to the value of 1.
Euler $$ e^{i \pi} + 1 = 0 regr.coef_ $$ 
Coeff $$ e^{i \pi} + 1 = 0 regr.score(X_test_data, Y_test_data) $$ 
$h(x) = {{regr.coef_}}$

display(Markdown(f'The value of a is {a}'))

<span style='color:Black;font-size: 250%'># Part 4. Use Cross Validation</span>

In [313]:
kf5 = KFold(n_splits=5, shuffle=False)
kf3 = KFold(n_splits=5, shuffle=False)

#cross_val_score(regr, X_test_data, Y_test_data, cv=5)

#One thousand
cross_val_score(regr, features, label, cv=5)

array([0.83918826, 0.87051239, 0.85871066, 0.87202623, 0.84364641])

Using the cross validation feature, the score values ranges from 0.84 to 0.87.
This is pretty much consistent in terms of being reliable in predicitng any data point.

<span style='color:Black;font-size: 250%'># Part 5. Perform Polynomial Regression</span>

In [314]:
from sklearn.preprocessing import PolynomialFeatures

#Using PolynomialFeatures and perform regression on augmented datast of degree 2
poly = PolynomialFeatures(degree=2)
poly_train = poly.fit_transform(X_train_data)
poly_test = poly.fit_transform(X_test_data)

regr = linear_model.LinearRegression()
regr.fit(poly_train, Y_train_data)


# Report metrics and output resultant equation.
print("Coefficients: \n", regr.coef_[0][5])
# The intercept
print("Intercept: \n", regr.intercept_)
# The score
print("Score: \n", regr.score(poly_test, Y_test_data))

Coefficients: 
 0.02857142871413702
Intercept: 
 [2.06597033e-05]
Score: 
 1.0


The score value is $regr.score(poly_test, Y_test_data)$ is 1, and it shows that polynomial regression of degree 2 is better than linear regression in terms of estimating values of data points.
Euler $$ e^{i \pi} + 1 = 0$$